version: 2

updates:
  - package-ecosystem: 'docker'
    directory: '/'
    open-pull-requests-limit: 1
    reviewers:
      - 'alexanderczigler'
      - 'osirisguitar'
    schedule:
      interval: 'weekly'

- package-ecosystem: 'github-actions'
    directory: '/'
    open-pull-requests-limit: 1
    reviewers:
      - 'alexanderczigler'
      - 'osirisguitar'
    schedule:
      interval: 'monthly'

  - package-ecosystem: 'npm'
    directory: '/'
    open-pull-requests-limit: 1
    reviewers:
      - 'alexanderczigler'
      - 'osirisguitar'
    schedule:
      interval: 'weekly'
