version: "3.8"

services:

  # Packages

  comprima-adapter:
    build: ./packages/comprima-adapter
    container_name: comprima-adapter
    environment:
    - COMPRIMA_SERVICE_URL_TEST
    - COMPRIMA_USER_TEST
    - COMPRIMA_PASSWORD_TEST
    - COMPRIMA_SERVICE_URL
    - COMPRIMA_USER
    - COMPRIMA_PASSWORD
    - ELASTICSEARCH_URL=http://elasticsearch:9200
    - POSTGRES__PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES__USER=readingroom
    depends_on:
    - elasticsearch
    networks:
    - digital-reading-room
    ports:
    - 14000:4000
    volumes:
    - ./packages/thumbnails:/thumbnails

  comprima-crawler:
    build: ./packages/comprima-crawler
    container_name: comprima-crawler
    environment:
    - COMPRIMA_URL=http://comprima-adapter:4000
    - LOG_LEVEL=debug
    - DATABASE_URL=postgres://crawler:${POSTGRES_PASSWORD}@postgres:5432/crawler
    - NODE_ENV=ci
    depends_on:
    - comprima-adapter
    networks:
    - digital-reading-room

  reading-room-frontend:
    build:
      context: ./packages/reading-room-frontend
      args:
      - COMPRIMA_ADAPTER_URL=http://localhost:14000
      - SEARCH_URL=http://localhost:14001
    container_name: reading-room-frontend
    depends_on:
    - comprima-adapter
    - reading-room-search
    networks:
    - digital-reading-room
    ports:
    - 14002:80

  reading-room-search:
    build: ./packages/reading-room-search
    container_name: reading-room-search
    environment:
    - DATABASE_URL=postgres://readingroom:${POSTGRES_PASSWORD}@postgres:5432/readingroom
    - ELASTIC_SEARCH__URL=http://elasticsearch:9200
    - NODE_ENV=ci
    depends_on:
    - comprima-adapter
    - elasticsearch
    - postgres
    networks:
    - digital-reading-room
    ports:
    - 14001:4001
    volumes:
    - ./packages/thumbnails:/thumbnails

  # Packages

  elasticsearch:
    container_name: elasticsearch
    environment:
    - xpack.security.enabled=false
    - "discovery.type=single-node"
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.1
    networks:
    - digital-reading-room
    ports:
    - 9200:9200
    volumes:
    - elasticsearch:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    depends_on:
    - elasticsearch
    environment:
    - ELASTICSEARCH_HOSTS=http://elastic-container:9200
    image: docker.elastic.co/kibana/kibana:8.4.1
    networks:
    - digital-reading-room
    ports:
    - 5601:5601

  postgres:
    build: dependencies/postgres
    container_name: postgres
    environment:
    - POSTGRES_PASSWORD
    networks:
    - digital-reading-room
    ports:
    - 5433:5432
    volumes:
    - postgres:/var/lib/postgresql/data

networks:
  digital-reading-room:
    driver: bridge

volumes:
  elasticsearch:
  postgres:
