import { ReactElement } from 'react'

import { Document, Dictionary } from '../../common/types'
import { createGeographyField, createMediaTypeField } from '../search'

export interface MetaDataFieldConfiguration {
  fieldName: string
  heading?: string
  formattingFunction?: (document: Document) => ReactElement
  type: MetaDataFieldType
  xs: number
  sm: number
  hasFields?: string[]
}

export enum MetaDataFieldType {
  TextField,
  Function,
  VisibleDivider,
  InvisibleDivider,
  Subheading,
}

export const metaDataFieldConfigurations: Dictionary<
  MetaDataFieldConfiguration[]
> = {
  Brandförsäkringsverket: [
    {
      fieldName: 'description',
      heading: 'BESKRIVNING',
      type: MetaDataFieldType.TextField,
      xs: 8,
      sm: 8,
    },
    {
      fieldName: 'divider1',
      type: MetaDataFieldType.InvisibleDivider,
      xs: 12,
      sm: 12,
    },
    {
      fieldName: 'motiveId',
      heading: 'MOTIVID',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'insuranceNumber',
      heading: 'FÖRSÄKRINGSNUMMER',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'business',
      heading: 'VERKSAMHET',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'year',
      heading: 'ÅR',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'divider2',
      type: MetaDataFieldType.VisibleDivider,
      xs: 12,
      sm: 12,
      hasFields: ['city', 'parish', 'region', 'street', 'areaMinor'],
    },
    {
      fieldName: 'city',
      heading: 'ORT',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'parish',
      heading: 'SOCKEN/FÖRSAMLING',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'region',
      heading: 'LÄN',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'street',
      heading: 'GATA',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'streetNumber',
      heading: 'GATUNUMMER',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'areaMinor',
      heading: 'AREA MINOR',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'divider2',
      type: MetaDataFieldType.VisibleDivider,
      xs: 12,
      sm: 12,
      hasFields: ['owner', 'seriesSignature', 'seriesName', 'volume'],
    },
    {
      fieldName: 'owner',
      heading: 'ÄGARE',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'seriesSignature',
      heading: 'SERIESIGNUM',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'seriesName',
      heading: 'SERIE',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'volume',
      heading: 'VOLYM',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
  ],
  default: [
    {
      fieldName: 'description',
      heading: 'BESKRIVNING',
      type: MetaDataFieldType.TextField,
      xs: 8,
      sm: 8,
    },
    {
      fieldName: 'divider1',
      type: MetaDataFieldType.InvisibleDivider,
      xs: 12,
      sm: 12,
    },
    {
      fieldName: 'time',
      heading: 'ÅRTAL',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'geography',
      heading: 'GEOGRAFI',
      type: MetaDataFieldType.Function,
      xs: 6,
      sm: 4,
      formattingFunction: createGeographyField,
    },
    {
      fieldName: 'mediaType',
      heading: 'MEDIETYP',
      type: MetaDataFieldType.Function,
      xs: 6,
      sm: 4,
      formattingFunction: createMediaTypeField,
    },
    {
      fieldName: 'motiveId',
      heading: 'MOTIVID',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'tags',
      heading: 'TAGGAR',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'originalText',
      heading: 'ORGINALTEXT',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'englishTitle',
      heading: 'ENGLISH TITLE',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'englishDescription',
      heading: 'ENGLISH DESCRIPTION',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'otherInfo',
      heading: 'Övrig information',
      type: MetaDataFieldType.Subheading,
      xs: 12,
      sm: 12,
    },
    {
      fieldName: 'depositor',
      heading: 'DEPONENT',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'seriesSignature',
      heading: 'SERIESIGNUM',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'seriesName',
      heading: 'SERIE',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'storage',
      heading: 'FÖRVARING/ORDNING',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'mediaCarrier',
      heading: 'MEDIEBÄRARE',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'volume',
      heading: 'VOLYM',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'album',
      heading: 'ALBUM',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'divider2',
      type: MetaDataFieldType.VisibleDivider,
      xs: 12,
      sm: 12,
      hasFields: ['creator', 'company'],
    },
    {
      fieldName: 'creator',
      heading: 'KREATÖR',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'company',
      heading: 'KREATÖR FIRMA',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'divider3',
      type: MetaDataFieldType.VisibleDivider,
      xs: 12,
      sm: 12,
      hasFields: [
        'block',
        'property',
        'parish',
        'areaMinor',
        'areaMajor',
        'municipality',
        'region',
        'street2',
        'streetNumber2',
        'property2',
        'block2',
      ],
    },
    {
      fieldName: 'block',
      heading: 'KVARTER',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'property',
      heading: 'FASTIGHET',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'parish',
      heading: 'FÖRSAMLING',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'areaMinor',
      heading: 'OMRÅDE MINDRE',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'areaMajor',
      heading: 'OMRÅDE STÖRRE',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'municipality',
      heading: 'KOMMUN',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'region',
      heading: 'LÄN',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'street2',
      heading: 'GATA 2',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'streetNumber2',
      heading: 'GATUNUMMER 2',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'property2',
      heading: 'FASTIGHET 2',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'block2',
      heading: 'KVARTER 2',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'divider2',
      type: MetaDataFieldType.VisibleDivider,
      xs: 12,
      sm: 12,
      hasFields: ['published', 'rights', 'language'],
    },
    {
      fieldName: 'language',
      heading: 'SPRÅK',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'published',
      heading: 'PUBLICERAD',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
    {
      fieldName: 'rights',
      heading: 'RÄTTIGHETER',
      type: MetaDataFieldType.TextField,
      xs: 6,
      sm: 4,
    },
  ],
}
